version: "3.8"

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: shibuya-mailpit
    restart: unless-stopped
    ports:
      - "52203:8025" # Web UI im Browser
      - "52401:1025" # SMTP Port für deine Anwendungen
    environment:
      - MP_MAX_MESSAGES=500
      - MP_DATABASE=/data/mailpit.db
    volumes:
      - shibuya_mailpit_data:/data

# Benannte Volumes für Datenpersistenz
volumes:
  shibuya_mailpit_data:
