# SHIBUYA Port Configuration
# Schema: {MONOREPO_PREFIX} (Prefix) + Category (1 Digit) + ID (2 Digits)

PACKAGES:
  kuroko: 1

APPS:
  angular-app: 1
  rust-api: 2

INFRA:
  infra-keycloak-admin: 1
  infra-shibuya-pgadmin: 2
  infra-shibuya-mailpit-web: 3

DB:
  infra-keycloak-db: 1
  infra-shibuya-db: 2

SMTP:
  infra-shibuya-mailpit-smtp: 1
