# SHIBUYA Port Configuration
# Schema: {MONOREPO_PREFIX} (Prefix) + Category (1 Digit) + ID (2 Digits)
# see `mokuroku/SUIDO.md` for more information

PACKAGES:
  kuroko: 1

APPS:
  angular-app: 1
  rust-api: 2

INFRA:
  infra-keycloak-admin: 1
  infra-shibuya-pgadmin: 2
  infra-shibuya-mailpit-web: 3

STORAGE:
  infra-keycloak-db: 1
  infra-shibuya-db: 2

COMM:
  infra-shibuya-mailpit-smtp: 1
